#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"
echo "-> Sincronizando repositório local com github..."
git pull &> /dev/null
version=$(git log -1 --format="%h (%ar)")
echo -e "-> Iniciando Nyaa... git $version\n"
ruby nyaa.rb
